// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SOLID_Transacoes.Infra.EntityFramework;

#nullable disable

namespace SOLIDTransacoes.Migrations
{
    [DbContext(typeof(EfSqliteAdapter))]
    partial class EfSqliteAdapterModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.2");

            modelBuilder.Entity("SOLID_Transacoes.Domain.Models.Parcela", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumeroParcela")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TransacaoId")
                        .HasColumnType("TEXT");

                    b.Property<double>("Valor")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("TransacaoId");

                    b.ToTable("Parcela", (string)null);
                });

            modelBuilder.Entity("SOLID_Transacoes.Domain.Models.Transacao", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("MetodoPagamento")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumeroParcelas")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Valor")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Transacoes", (string)null);
                });

            modelBuilder.Entity("SOLID_Transacoes.Domain.Models.Parcela", b =>
                {
                    b.HasOne("SOLID_Transacoes.Domain.Models.Transacao", null)
                        .WithMany("Parcelas")
                        .HasForeignKey("TransacaoId");
                });

            modelBuilder.Entity("SOLID_Transacoes.Domain.Models.Transacao", b =>
                {
                    b.Navigation("Parcelas");
                });
#pragma warning restore 612, 618
        }
    }
}
